### ISSUE TITLE
Catkinize and release for groovy

### ISSUE THREAD

**Issue by stwirth** [srv/viso2#11]
The package should be catkinized and released for groovy.
1. We should rename the branches:
   
   `master`->`fuerte`
   `develop`->`fuerte-devel`
2. Branch off new branches `groovy` and `groovy-devel`
3. Catkinize `groovy-devel` branch and merge to `groovy` when finished
4. Point default branch (HEAD) to `groovy`
5. Update rosdistro files for fuerte and groovy.

**Comment by miquelmassot** [comment]
Hi Stephan!

I created a groovy_testing branch where I've tried to migrate from rosbuild to catkin build system. However I've not been able to include the original libviso2 headers from viso2_ros cpp files. 

```
Building CXX object viso2/viso2_ros/CMakeFiles/mono_odometer.dir/src/mono_odometer.cpp.o
[100%] Building CXX object viso2/viso2_ros/CMakeFiles/stereo_odometer.dir/src/stereo_odometer.cpp.o
/home/miquel/catkin_ws/src/viso2/viso2_ros/src/mono_odometer.cpp:8:23: fatal error: viso_mono.h: No such file or directory
compilation terminated.
/home/miquel/catkin_ws/src/viso2/viso2_ros/src/stereo_odometer.cpp:8:25: fatal error: viso_stereo.h: No such file or directory
compilation terminated.
make[2]: *** [viso2/viso2_ros/CMakeFiles/mono_odometer.dir/src/mono_odometer.cpp.o] Error 1
make[1]: *** [viso2/viso2_ros/CMakeFiles/mono_odometer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [viso2/viso2_ros/CMakeFiles/stereo_odometer.dir/src/stereo_odometer.cpp.o] Error 1
make[1]: *** [viso2/viso2_ros/CMakeFiles/stereo_odometer.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed
```

This branch does not compile due to this. I checked how the header files are included from mono and stereo_odometer.cpp, and they do not follow the `<package/header.h>` naming.

Could you take a look at it?

Once this catkinization is done, fovis will be a copy/paste =)

**Comment by miquelmassot** [comment]
I've been able to compile viso2 in groovy. Please test it and let me know if it works for you.

**Comment by stwirth** [comment]
Works great! Thank you! I'll update the rosdistro files.

**Comment by stwirth** [comment]
Pull request for rosdistro is: ros/rosdistro#654. I changed the default branch of this repo to groovy as well (in github settings).
